export const POST_ACTIONS = {
  FETCH_ALL: 'FETCH_POSTS',
  FETCH: 'FETCH_POST'
}

export const COMMENT_ACTIONS = {
  FETCH_ALL: 'FETCH_COMMENTS'
}

export const SUBSCRIPTION_ACTIONS = {
  TOGGLE_OPEN: 'TOGGLE_OPEN'
}

export const APP_ACTIONS = {
  TOGGLE_LOAD: 'TOGGLE_LOAD'
}