import React from 'react';
import PropTypes from 'prop-types';
import clsx from 'clsx';
import Select from 'react-select';
import { emphasize, makeStyles, useTheme } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';
import NoSsr from '@material-ui/core/NoSsr';
import TextField from '@material-ui/core/TextField';
import Paper from '@material-ui/core/Paper';
import Chip from '@material-ui/core/Chip';
import MenuItem from '@material-ui/core/MenuItem';
import CancelIcon from '@material-ui/icons/Cancel';

const suggestions = [
  { label : 'EDS' },
{ label : 'BTU' },
{ label : 'BJS' },
{ label : 'NUE' },
{ label : 'NT' },
{ label : 'IR' },
{ label : 'AVP' },
{ label : 'UMC' },
{ label : 'SUN' },
{ label : 'JCP' },
{ label : 'CHK' },
{ label : 'TKC' },
{ label : 'EOP' },
{ label : 'RIMM' },
{ label : 'ABV' },
{ label : 'KMG' },
{ label : 'PCU' },
{ label : 'NBR' },
{ label : 'TVE' },
{ label : 'AMT' },
{ label : 'STX' },
{ label : 'TLD' },
{ label : 'KUB' },
{ label : 'EDP' },
{ label : 'MAS' },
{ label : 'GNW' },
{ label : 'NIPNY' },
{ label : 'PLD' },
{ label : 'VNO' },
{ label : 'SNDK' },
{ label : 'CPB' },
{ label : 'SRE' },
{ label : 'GGP' },
{ label : 'ATE' },
{ label : 'NFB' },
{ label : 'EQR' },
{ label : 'WWY' },
{ label : 'TCA^' },
{ label : 'RUK' },
{ label : 'MTB' },
{ label : 'KNBWY' },
{ label : 'TKA' },
{ label : 'CELG' },
{ label : 'IGT' },
{ label : 'AHO' },
{ label : 'KTC' },
{ label : 'FCX' },
{ label : 'ABV/C' },
{ label : 'LUX' },
{ label : 'CUK' },
{ label : 'XL' },
{ label : 'PCAR' },
{ label : 'LU' },
{ label : 'PT' },
{ label : 'TJX' },
{ label : 'KMI' },
{ label : 'RIN' },
{ label : 'ROK' },
{ label : 'DHI' },
{ label : 'GFI' },
{ label : 'CSX' },
{ label : 'NTAP' },
{ label : 'ED' },
{ label : 'PPL' },
{ label : 'OTE' },
{ label : 'NTRS' },
{ label : 'RG' },
{ label : 'HNZ' },
{ label : 'LLTC' },
{ label : 'ROH' },
{ label : 'JWN' },
{ label : 'PDG' },
{ label : 'CN' },
{ label : 'Q' },
{ label : 'EWJ' },
{ label : 'CHU' },
{ label : 'TXT' },
{ label : 'AES' },
{ label : 'BBBY' },
{ label : 'ENB' },
{ label : 'NE' },
{ label : 'PGN' },
{ label : 'FO' },
{ label : 'AOC' },
{ label : 'ASML' },
{ label : 'DO' },
{ label : 'RTRSY' },
{ label : 'FIA' },
{ label : 'CAG' },
{ label : 'UPM' },
{ label : 'UU' },
{ label : 'CIT' },
{ label : 'MUR' },
{ label : 'MGM' },
{ label : 'SWY' },
{ label : 'ENL' },
{ label : 'ADO' },
{ label : 'F^A' },
{ label : 'PSO' },
{ label : 'CEG' },
{ label : 'AEE' },
{ label : 'SNP' },
{ label : 'PHM' },
{ label : 'KLAC' },
{ label : 'JNPR' },
{ label : 'ODP' },
{ label : 'AMP' },
{ label : 'GLH' },
{ label : 'WFMI' },
{ label : 'DGX' },
{ label : 'TROW' },
{ label : 'PPG' },
{ label : 'ASN' },
{ label : 'ET' },
{ label : 'MI' },
{ label : 'CM' },
{ label : 'EPD' },
{ label : 'XLNX' },
{ label : 'ETN' },
{ label : 'APOL' },
{ label : 'PBI' },
{ label : 'LLL' },
{ label : 'N' },
{ label : 'TDK' },
{ label : 'CVH' },
{ label : 'UB' },
{ label : 'VIP' },
{ label : 'ASO' },
{ label : 'SII' },
{ label : 'NSM' },
{ label : 'HLT' },
{ label : 'LTD' },
{ label : 'ITT' },
{ label : 'LNC' },
{ label : 'BMET' },
{ label : 'PSA' },
{ label : 'SNN' },
{ label : 'ADSK' },
{ label : 'CSC' },
{ label : 'TNT' },
{ label : 'CCE' },
{ label : 'POT' },
{ label : 'DOV' },
{ label : 'TV' },
{ label : 'GG' },
{ label : 'ABS' },
{ label : 'INTU' },
{ label : 'HSY' },
{ label : 'MT' },
{ label : 'ECL' },
{ label : 'CTX' },
{ label : 'SEO' },
{ label : 'MU' },
{ label : 'HUM' },
{ label : 'PH' },
{ label : 'CMA' },
{ label : 'SAN' },
{ label : 'CLX' },
{ label : 'TRB' },
{ label : 'AUO' },
{ label : 'EP' },
{ label : 'BXP' },
{ label : 'CIN' },
{ label : 'EOC' },
{ label : 'SNV' },
{ label : 'EEM' },
{ label : 'CHIR' },
{ label : 'RCL' },
{ label : 'MDY' },
{ label : 'IACI' },
{ label : 'MIR' },
{ label : 'MEDI' },
{ label : 'RYAAY' },
{ label : 'HAN' },
{ label : 'JBL' },
{ label : 'ZION' },
{ label : 'EXPE' },
{ label : 'IVX' },
{ label : 'MBI' },
{ label : 'IWM' },
{ label : 'SRA' },
{ label : 'FSH' },
{ label : 'AMTD' },
{ label : 'ABK' },
{ label : 'FISV' },
{ label : 'NBL' },
{ label : 'CNA' },
{ label : 'COL' },
{ label : 'UPL' },
{ label : 'HRB' },
{ label : 'MGA' },
{ label : 'KIM' },
{ label : 'CINF' },
{ label : 'VAR' },
{ label : 'HTX' },
{ label : 'ENI' },
{ label : 'SID' },
{ label : 'MCHP' },
{ label : 'CHS' },
{ label : 'SHPGY' },
{ label : 'EXPD' },
{ label : 'ESV' },
{ label : 'LEN' },
{ label : 'AAA' },
{ label : 'XEL' },
{ label : 'JP' },
{ label : 'LH' },
{ label : 'TSP' },
{ label : 'SOV' },
{ label : 'ICI' },
{ label : 'NVDA' },
{ label : 'KMP' },
{ label : 'DIA' },
{ label : 'FLR' },
{ label : 'CP' },
{ label : 'NZT' },
{ label : 'LFC' },
{ label : 'UVN' },
{ label : 'ASD' },
{ label : 'SIRI' },
{ label : 'DTE' },
{ label : 'AZO' },
{ label : 'AVZ' },
{ label : 'CBE' },
{ label : 'NIHD' },
{ label : 'PUB' },
{ label : 'FMS' },
{ label : 'HCBK' },
{ label : 'GPC' },
{ label : 'ACS' },
{ label : 'KBH' },
{ label : 'HMY' },
{ label : 'AVB' },
{ label : 'VMC' },
{ label : 'IPR' },
{ label : 'SHW' },
{ label : 'CTSH' },
{ label : 'HAR' },
{ label : 'CCH' },
{ label : 'EK' },
{ label : 'SWN' },
{ label : 'DVY' },
{ label : 'HSP' },
{ label : 'SDX' },
{ label : 'CTAS' },
{ label : 'BRL' },
{ label : 'HMT' },
{ label : 'IFX' },
{ label : 'RRD' },
{ label : 'ALTR' },
{ label : 'BPO' },
{ label : 'PBG' },
{ label : 'STR' },
{ label : 'CHRW' },
{ label : 'PIXR' },
{ label : 'CPL' },
{ label : 'WEN' },
{ label : 'FNF' },
{ label : 'PXD' },
{ label : 'NCR' },
{ label : 'FSL/B' },
{ label : 'PCL' },
{ label : 'DASTY' },
{ label : 'ELN' },
{ label : 'X' },
{ label : 'BDK' },
{ label : 'CCI' },
{ label : 'CNX' },
{ label : 'AWC' },
{ label : 'GRMN' },
{ label : 'NFX' },
{ label : 'IHG' },
{ label : 'MAT' },
{ label : 'BCR' },
{ label : 'PCP' },
{ label : 'SFA' },
{ label : 'TKP' },
{ label : 'BG' },
{ label : 'BAB' },
{ label : 'TU' },
{ label : 'JOYG' },
{ label : 'RSA' },
{ label : 'DEG' },
{ label : 'NWL' },
{ label : 'PTEN' },
{ label : 'DOX' },
{ label : 'SAFC' },
{ label : 'GRP' },
{ label : 'WYNN' },
{ label : 'UST' },
{ label : 'GWW' },
{ label : 'SAY' },
{ label : 'GGB' },
{ label : 'LRCX' },
{ label : 'BER' },
{ label : 'KSE' },
{ label : 'PHI' },
{ label : 'ERF' },
{ label : 'HRS' },
{ label : 'RHI' },
{ label : 'HDB' },
{ label : 'VFC' },
{ label : 'DRI' },
{ label : 'AKH' },
{ label : 'STP' },
{ label : 'SSP' },
{ label : 'AMOV' },
{ label : 'VRSN' },
{ label : 'CBSS' },
{ label : 'UNM' },
{ label : 'TTM' },
{ label : 'SEPR' },
{ label : 'AIZ' },
{ label : 'WPO' },
{ label : 'WFR' },
{ label : 'FLEX' },
{ label : 'MTG' },
{ label : 'RE' },
{ label : 'AVY' },
{ label : 'OCR' },
{ label : 'LYO' },
{ label : 'MOS' },
{ label : 'AN' },
{ label : 'DISH' },
{ label : 'TMK' },
{ label : 'ANF' },
{ label : 'XMSR' },
{ label : 'CBH' },
{ label : 'STOSY' },
{ label : 'FAST' },
{ label : 'MHK' },
{ label : 'TLAB' },
{ label : 'TLWT' },
{ label : 'WTM' },
{ label : 'PDE' },
{ label : 'RX' },
{ label : 'LUK' },
{ label : 'AYE' },
{ label : 'HNT' },
{ label : 'FMX' },
{ label : 'LXK' },
{ label : 'IWD' },
{ label : 'TMS' },
{ label : 'ACI' },
{ label : 'NI' },
{ label : 'BOT' },
{ label : 'DVA' },
{ label : 'CVC' },
{ label : 'CGA' },
{ label : 'CMVT' },
{ label : 'CAM' },
{ label : 'IRM' },
{ label : 'WSH' },
{ label : 'TMO' },
{ label : 'WHR' },
{ label : 'CTXS' },
{ label : 'BPOP' },
{ label : 'NTLI' },
{ label : 'TIF' },
{ label : 'DDR' },
{ label : 'DG' },
{ label : 'VTI' },
{ label : 'ABI' },
{ label : 'HBAN' },
{ label : 'CHA' },
{ label : 'STZ' },
{ label : 'TOL' },
{ label : 'TIN' },
{ label : 'CHKP' },
{ label : 'RSG' },
{ label : 'NXTP' },
{ label : 'RHAT' },
{ label : 'DF' },
{ label : 'ATI' },
{ label : 'REXMY' },
{ label : 'MAC' },
{ label : 'GYI' },
{ label : 'HMA' },
{ label : 'MNST' },
{ label : 'SJR' },
{ label : 'CDNS' },
{ label : 'TSO' },
{ label : 'EFX' },
{ label : 'JDSU' },
{ label : 'AV' },
{ label : 'AC' },
{ label : 'ORI' },
{ label : 'LBTYA' },
{ label : 'RDC' },
{ label : 'DRE' },
{ label : 'ISRG' },
{ label : 'BCH' },
{ label : 'ERJ' },
{ label : 'WEC' },
{ label : 'JEC' },
{ label : 'WTW' },
{ label : 'MWV' },
{ label : 'GR' },
{ label : 'EC' },
{ label : 'MTA' },
{ label : 'DNB' },
{ label : 'LBTYK' },
{ label : 'BMC' },
{ label : 'IWF' },
{ label : 'JOE' },
{ label : 'SANYY' },
{ label : 'FHN' },
{ label : 'HUN' },
{ label : 'PDCO' },
{ label : 'RDN' },
{ label : 'ASH' },
{ label : 'WDC' },
{ label : 'AAP' },
{ label : 'CKFR' },
{ label : 'MAN' },
{ label : 'MRBK' },
{ label : 'AMLN' },
{ label : 'WAT' },
{ label : 'MX' },
{ label : 'TNE' },
{ label : 'BF/B' },
{ label : 'EL' },
{ label : 'APCC' },
{ label : 'CBG' },
{ label : 'HRL' },
{ label : 'ASBC' },
{ label : 'NYB' },
{ label : 'SCG' },
{ label : 'WSM' },
{ label : 'KRI' },
{ label : 'SEE' },
{ label : 'BEAS' },
{ label : 'STN' },
{ label : 'CMI' },
{ label : 'AMCR' },
{ label : 'KG' },
{ label : 'LEG' },
{ label : 'APH' },
{ label : 'JNS' },
{ label : 'MIK' },
{ label : 'URBN' },
{ label : 'ATYT' },
{ label : 'FAF' },
{ label : 'AXS' },
{ label : 'CDWC' },
{ label : 'CC' },
{ label : 'AMB' },
{ label : 'EQT' },
{ label : 'TMIC' },
{ label : 'IPS' },
{ label : 'CRM' },
{ label : 'LAF' },
{ label : 'NVR' },
{ label : 'PCW' },
{ label : 'CSB' },
{ label : 'STU' },
{ label : 'REG' },
{ label : 'SIAL' },
{ label : 'CTL' },
{ label : 'POM' },
{ label : 'SVU' },
{ label : 'IPG' },
{ label : 'PBCT' },
{ label : 'MDU' },
{ label : 'CIG' },
{ label : 'TKS' },
{ label : 'MYL' },
{ label : 'USG' },
{ label : 'SHY' },
{ label : 'GTK' },
{ label : 'XRAY' },
{ label : 'PNW' },
{ label : 'GLG' },
{ label : 'BLL' },
{ label : 'TRH' },
{ label : 'PDS' },
{ label : 'BF/A' },
{ label : 'LAMR' },
{ label : 'ASX' },
{ label : 'FII' },
{ label : 'MKTAY' },
{ label : 'ROST' },
{ label : 'CEPH' },
{ label : 'ISIL' },
{ label : 'LNCR' },
{ label : 'ARW' },
{ label : 'ALV' },
{ label : 'SWK' },
{ label : 'NVT' },
{ label : 'CZN' },
{ label : 'SEIC' },
{ label : 'TAC' },
{ label : 'IJR' },
{ label : 'HP' },
{ label : 'NYT' },
{ label : 'ACV' },
{ label : 'AMR' },
{ label : 'AIV' },
{ label : 'HSIC' },
{ label : 'DISCA' },
{ label : 'ETP' },
{ label : 'SFI' },
{ label : 'GPN' },
{ label : 'BYD' },
{ label : 'AEOS' },
{ label : 'MTL' },
{ label : 'PPDI' },
{ label : 'LRY' },
{ label : 'BRO' },
{ label : 'CNP' },
{ label : 'ACGL' },
{ label : 'ACF' },
{ label : 'EMN' },
{ label : 'MLM' },
{ label : 'NVLS' },
{ label : 'ATVI' },
{ label : 'DST' },
{ label : 'NRG' },
{ label : 'MFE' },
{ label : 'ALD' },
{ label : 'PNR' },
{ label : 'BNL' },
{ label : 'RRC' },
{ label : 'TSS' },
{ label : 'PMI' },
{ label : 'ACAS' },
{ label : 'TAP' },
{ label : 'CNB' },
{ label : 'MICC' },
{ label : 'KWK' },
{ label : 'BVN' },
{ label : 'IJD' },
{ label : 'ENDP' },
{ label : 'VRTX' },
{ label : 'HAS' },
{ label : 'NOVL' },
{ label : 'HCP' },
{ label : 'SVM' },
{ label : 'LOGI' },
{ label : 'XEC' },
{ label : 'MDR' },
{ label : 'EV' },
{ label : 'FDO' },
{ label : 'LIZ' },
{ label : 'BEC' },
{ label : 'CPS' },
{ label : 'CNO' },
{ label : 'CYN' },
{ label : 'JBHT' },
{ label : 'BDM' },
{ label : 'ORLY' },
{ label : 'EAS' },
{ label : 'WPI' },
{ label : 'JNY' },
{ label : 'IVGN' },
{ label : 'TRZ' },
{ label : 'CXG' },
{ label : 'BC' },
{ label : 'OSK' },
{ label : 'TSN' },
{ label : 'WTR' },
{ label : 'BOL' },
{ label : 'WRI' },
{ label : 'WES' },
{ label : 'BVF' },
{ label : 'AGE' },
{ label : 'PPP' },
{ label : 'PETM' },
{ label : 'PLL' },
{ label : 'CEN' },
{ label : 'LSI' },
{ label : 'MIL' },
{ label : 'WGR' },
{ label : 'MKC' },
{ label : 'AVT' },
{ label : 'SLG' },
{ label : 'FTI' },
{ label : 'TE' },
{ label : 'CVD' },
{ label : 'FL' },
{ label : 'FRK' },
{ label : 'RBK' },
{ label : 'TRI' },
{ label : 'FSL' },
{ label : 'FRT' },
{ label : 'EPE' },
{ label : 'PXP' },
{ label : 'JNC' },
{ label : 'EAT' },
{ label : 'PRE' },
{ label : 'TIP' },
{ label : 'RL' },
{ label : 'UDR' },
{ label : 'TEX' },
{ label : 'SPIL' },
{ label : 'LNT' },
{ label : 'ADS' },
{ label : 'ROP' },
{ label : 'CBSH' },
{ label : 'DADE' },
{ label : 'COGN' },
{ label : 'OSI' },
{ label : 'CERN' },
{ label : 'NDAQ' },
{ label : 'HCC' },
{ label : 'TER' },
{ label : 'CYTC' },
{ label : 'SLR' },
{ label : 'THC' },
{ label : 'DNR' },
{ label : 'CPT' },
{ label : 'ENR' },
{ label : 'CYH' },
{ label : 'RYL' },
{ label : 'IMDC' },
{ label : 'SMG' },
{ label : 'TDW' },
{ label : 'OI' },
{ label : 'IIT' },
{ label : 'TKR' },
{ label : 'TCB' },
{ label : 'CRL' },
{ label : 'AKAM' },
{ label : 'EXBD' },
{ label : 'GSL' },
{ label : 'UTIW' },
{ label : 'HSC' },
{ label : 'GLD' },
{ label : 'RA' },
{ label : 'PDLI' },
{ label : 'ICBC' },
{ label : 'ERIE' },
{ label : 'MKL' },
{ label : 'PAS' },
{ label : 'DPL' },
{ label : 'CDIS' },
{ label : 'WFSI' },
{ label : 'RJF' },
{ label : 'SSCC' },
{ label : 'CE' },
{ label : 'RYN' },
{ label : 'RCI' },
{ label : 'RNR' },
{ label : 'TSG' },
{ label : 'BMS' },
{ label : 'MLNM' },
{ label : 'DAIEY' },
{ label : 'FST' },
{ label : 'CPWR' },
{ label : 'QLGC' },
{ label : 'SNPS' },
{ label : 'FHR' },
{ label : 'PTV' },
{ label : 'CMS' },
{ label : 'CECO' },
{ label : 'RMK' },
{ label : 'MEE' },
{ label : 'ZBRA' },
{ label : 'IJH' },
{ label : 'JEF' },
{ label : 'HNI' },
{ label : 'SIG' },
{ label : 'VTR' },
{ label : 'ESI' },
{ label : 'AMG' },
{ label : 'PAA' },
{ label : 'KNM' },
{ label : 'CG' },
{ label : 'BWA' },
{ label : 'SPW' },
{ label : 'ANAT' },
{ label : 'KMX' },
{ label : 'PL' },
{ label : 'SPP' },
{ label : 'BCO' },
{ label : 'AGU' },
{ label : 'CCK' },
{ label : 'RHA' },
{ label : 'IM' },
{ label : 'LPX' },
{ label : 'LZ' },
{ label : 'CHH' },
{ label : 'SBL' },
{ label : 'JHX' },
{ label : 'HUG' },
{ label : 'GIB' },
{ label : 'HPT' },
{ label : 'RRI' },
{ label : 'CSE' },
{ label : 'HCR' },
{ label : 'MCY' },
{ label : 'IVW' },
{ label : 'NST' },
{ label : 'SON' },
{ label : 'LVLT' },
{ label : 'SMI' },
{ label : 'APCS' },
{ label : 'IFF' },
{ label : 'IVE' },
{ label : 'ACH' },
{ label : 'IFIN' },
{ label : 'MOLX' },
{ label : 'UTR' },
{ label : 'ARI' },
{ label : 'RGA' },
{ label : 'BOKF' },
{ label : 'PA' },
{ label : 'IMCL' },
{ label : 'AF' },
{ label : 'EYE' },
{ label : 'HB' },
{ label : 'CEM' },
{ label : 'CBI' },
{ label : 'AW' },
{ label : 'BZH' },
{ label : 'FRO' },
{ label : 'RSH' },
{ label : 'ARG' },
{ label : 'CLE' },
{ label : 'NU' },
{ label : 'WMG' },
{ label : 'SFD' },
{ label : 'PKI' },
{ label : 'ADCT' },
{ label : 'XLE' },
{ label : 'TK' },
{ label : 'CFR' },
{ label : 'RMBS' },
{ label : 'AFG' },
{ label : 'GPM' },
{ label : 'NIS' },
{ label : 'YRCW' },
{ label : 'CAKE' },
{ label : 'F^S' },
{ label : 'GIL' },
{ label : 'AME' },
{ label : 'SGMS' },
{ label : 'AVX' },
{ label : 'R' },
{ label : 'FIC' },
{ label : 'BDN' },
{ label : 'EGN' },
{ label : 'IWN' },
{ label : 'NCX' },
{ label : 'DCI' },
{ label : 'ATK' },
{ label : 'WSTC' },
{ label : 'FCE/A' },
{ label : 'MDC' },
{ label : 'SHU' },
{ label : 'SGR' },
{ label : 'ICE' },
{ label : 'FULT' },
{ label : 'PNP' },
{ label : 'JLG' },
{ label : 'WL' },
{ label : 'BUH' },
{ label : 'BAP' },
{ label : 'SUG' },
{ label : 'RMD' },
{ label : 'BKS' },
{ label : 'ATG' },
{ label : 'NFG' },
{ label : 'AJG' },
{ label : 'SKYF' },
{ label : 'IDTI' },
{ label : 'CMC' },
{ label : 'CLI' },
{ label : 'FWLT' },
{ label : 'GT' },
{ label : 'OKE' },
{ label : 'UNT' },
{ label : 'GGG' },
{ label : 'VAL' },
{ label : 'THE' },
{ label : 'MDZ' },
{ label : 'LI' },
{ label : 'VIA' },
{ label : 'BOBJ' },
{ label : 'MDG' },
{ label : 'TNB' },
{ label : 'SFG' },
{ label : 'PZE' },
{ label : 'CBL' },
{ label : 'USM' },
{ label : 'DBD' },
{ label : 'TIE' },
{ label : 'TMA' },
{ label : 'SKS' },
{ label : 'VSH' },
{ label : 'CNF' },
{ label : 'FTO' },
{ label : 'PENN' },
{ label : 'BOH' },
{ label : 'SPF' },
{ label : 'SLAB' },
{ label : 'SRP' },
{ label : 'AGG' },
{ label : 'DLTR' },
{ label : 'SRCL' },
{ label : 'WTI' },
{ label : 'NLC' },
{ label : 'RS' },
{ label : 'KMR' },
{ label : 'NDE' },
{ label : 'NATI' },
{ label : 'FMS^' },
{ label : 'BLK' },
{ label : 'GOL' },
{ label : 'VLY' },
{ label : 'THG' },
{ label : 'HLTH' },
{ label : 'RESP' },
{ label : 'GNTX' },
{ label : 'LAUR' },
{ label : 'TPP' },
{ label : 'FFH' },
{ label : 'PWI' },
{ label : 'IRF' },
{ label : 'NXL' },
{ label : 'GPRO' },
{ label : 'FFIV' },
{ label : 'BRE' },
{ label : 'TFX' },
{ label : 'EW' },
{ label : 'VSL' },
{ label : 'TRW' },
{ label : 'KCI' },
{ label : 'FLS' },
{ label : 'SJM' },
{ label : 'AFFX' },
{ label : 'WBS' },
{ label : 'COG' },
{ label : 'CNH' },
{ label : 'TRN' },
{ label : 'WSC' },
{ label : 'PKG' },
{ label : 'SCO' },
{ label : 'LSTR' },
{ label : 'MEOH' },
{ label : 'PIO' },
{ label : 'SM' },
{ label : 'COO' },
{ label : 'CBT' },
{ label : 'WLT' },
{ label : 'IDXX' },
{ label : 'OGE' },
{ label : 'CVA' },
{ label : 'DNP' },
{ label : 'NFS' },
{ label : 'PSD' },
{ label : 'SOSA' },
{ label : 'SCI' },
{ label : 'ARMHY' },
{ label : 'ABER' },
{ label : 'ANN' },
{ label : 'APPX' },
{ label : 'UHS' },
{ label : 'THO' },
{ label : 'CNT' },
{ label : 'HLF' },
{ label : 'HAVS' },
{ label : 'LFL' },
{ label : 'LIHRY' },
{ label : 'CVG' },
{ label : 'TEK' },
{ label : 'IEX' },
{ label : 'MTD' },
{ label : 'CBD' },
{ label : 'AEM' },
{ label : 'FCS' },
{ label : 'IWO' },
{ label : 'LCC' },
{ label : 'MOLXA' },
{ label : 'KZL' },
{ label : 'AMH' },
{ label : 'DJ' },
{ label : 'CHD' },
{ label : 'CLF' },
{ label : 'IWB' },
{ label : 'XOM' },
{ label : 'GE' },
{ label : 'MSFT' },
{ label : 'BP' },
{ label : 'C' },
{ label : 'PG' },
{ label : 'WMT' },
{ label : 'PFE' },
{ label : 'HBC' },
{ label : 'TM' },
{ label : 'JNJ' },
{ label : 'BAC' },
{ label : 'AIG' },
{ label : 'TOT' },
{ label : 'NVS' },
{ label : 'MO' },
{ label : 'GSK' },
{ label : 'MTU' },
{ label : 'JPM' },
{ label : 'RDS/A' },
{ label : 'CVX' },
{ label : 'SNY' },
{ label : 'VOD' },
{ label : 'INTC' },
{ label : 'IBM' },
{ label : 'E' },
{ label : 'CSCO' },
{ label : 'BRK/A' },
{ label : 'UBS' },
{ label : 'WFC' },
{ label : 'T' },
{ label : 'RDS/B' },
{ label : 'KO' },
{ label : 'CHL' },
{ label : 'PEP' },
{ label : 'VZ' },
{ label : 'COP' },
{ label : 'DNA' },
{ label : 'AMGN' },
{ label : 'STD' },
{ label : 'HPQ' },
{ label : 'GOOG' },
{ label : 'HD' },
{ label : 'WB' },
{ label : 'SI' },
{ label : 'NOK' },
{ label : 'UNH' },
{ label : 'TWX' },
{ label : 'QCOM' },
{ label : 'ING' },
{ label : 'DCM' },
{ label : 'EON' },
{ label : 'AZN' },
{ label : 'MRK' },
{ label : 'SLB' },
{ label : 'TEF' },
{ label : 'MBT' },
{ label : 'NTT' },
{ label : 'BHP' },
{ label : 'CSR' },
{ label : 'BCS' },
{ label : 'DELL' },
{ label : 'MER' },
{ label : 'BBV' },
{ label : 'MDT' },
{ label : 'ABT' },
{ label : 'DT' },
{ label : 'AXP' },
{ label : 'MS' },
{ label : 'SAP' },
{ label : 'S' },
{ label : 'ORCL' },
{ label : 'LLY' },
{ label : 'AZ' },
{ label : 'GS' },
{ label : 'AAPL' },
{ label : 'AXA' },
{ label : 'WYE' },
{ label : 'STO' },
{ label : 'EBAY' },
{ label : 'PBR' },
{ label : 'UTX' },
{ label : 'FTE' },
{ label : 'AAUK' },
{ label : 'DCX' },
{ label : 'DB' },
{ label : 'ERICY' },
{ label : 'MOT' },
{ label : 'FNM' },
{ label : 'BA' },
{ label : 'MMM' },
{ label : 'SPY' },
{ label : 'RTP' },
{ label : 'USB' },
{ label : 'CAJ' },
{ label : 'TSM' },
{ label : 'MC' },
{ label : 'TYC' },
{ label : 'ABN' },
{ label : 'HMC' },
{ label : 'EN' },
{ label : 'BLS' },
{ label : 'LYG' },
{ label : 'NSANY' },
{ label : 'RY' },
{ label : 'LOW' },
{ label : 'SNE' },
{ label : 'YHOO' },
{ label : 'DIS' },
{ label : 'MFC' },
{ label : 'TGT' },
{ label : 'TEM' },
{ label : 'BTI' },
{ label : 'UPS' },
{ label : 'WLP' },
{ label : 'TXN' },
{ label : 'SZE' },
{ label : 'FRE' },
{ label : 'BBL' },
{ label : 'CAT' },
{ label : 'BMY' },
{ label : 'PHG' },
{ label : 'MCD' },
{ label : 'WAG' },
{ label : 'DEO' },
{ label : 'ECA' },
{ label : 'BF' },
{ label : 'AMX' },
{ label : 'WM' },
{ label : 'NAB' },
{ label : 'HAL' },
{ label : 'DOW' },
{ label : 'UN' },
{ label : 'BRG' },
{ label : 'PBR/A' },
{ label : 'OXY' },
{ label : 'ACL' },
{ label : 'BNS' },
{ label : 'VLO' },
{ label : 'RIO' },
{ label : 'NMR' },
{ label : 'EXC' },
{ label : 'PRU' },
{ label : 'MET' },
{ label : 'TD' },
{ label : 'CMCSA' },
{ label : 'LEH' },
{ label : 'TI' },
{ label : 'GLW' },
{ label : 'SU' },
{ label : 'V' },
{ label : 'DD' },
{ label : 'BEN' },
{ label : 'APC' },
{ label : 'ADP' },
{ label : 'APA' },
{ label : 'BBY' },
{ label : 'HIG' },
{ label : 'PCZ' },
{ label : 'SLF' },
{ label : 'GDT' },
{ label : 'PUK' },
{ label : 'BRK/B' },
{ label : 'CX' },
{ label : 'BK' },
{ label : 'SBUX' },
{ label : 'TXU' },
{ label : 'CNI' },
{ label : 'ADBE' },
{ label : 'HIT' },
{ label : 'ITW' },
{ label : 'COST' },
{ label : 'AFL' },
{ label : 'UNP' },
{ label : 'BCM' },
{ label : 'SLM' },
{ label : 'TOC' },
{ label : 'IX' },
{ label : 'GD' },
{ label : 'AT' },
{ label : 'BAX' },
{ label : 'MITSY' },
{ label : 'MON' },
{ label : 'ABB' },
{ label : 'CVS' },
{ label : 'BCE' },
{ label : 'L' },
{ label : 'TLM' },
{ label : 'COF' },
{ label : 'CMX' },
{ label : 'CMCSK' },
{ label : 'NOC' },
{ label : 'GDW' },
{ label : 'QQQQ' },
{ label : 'NSC' },
{ label : 'BBT' },
{ label : 'NCC' },
{ label : 'YPF' },
{ label : 'PTR' },
{ label : 'WIT' },
{ label : 'ITY' },
{ label : 'EFA' },
{ label : 'KPN' },
{ label : 'FITB' },
{ label : 'VE' },
{ label : 'CSG' },
{ label : 'PGR' },
{ label : 'INFY' },
{ label : 'ADM' },
{ label : 'HCA' },
{ label : 'EOG' },
{ label : 'SYK' },
{ label : 'PKX' },
{ label : 'CFC' },
{ label : 'STT' },
{ label : 'SYMC' },
{ label : 'BRCM' },
{ label : 'AIB' },
{ label : 'BBD' },
{ label : 'MRVL' },
{ label : 'SHLD' },
{ label : 'DTV' },
{ label : 'TS' },
{ label : 'ACN' },
{ label : 'ALA' },
{ label : 'MHP' },
{ label : 'SCHW' },
{ label : 'SPI' },
{ label : 'SYY' },
{ label : 'PNC' },
{ label : 'SCM' },
{ label : 'CB' },
{ label : 'AMD' },
{ label : 'MCO' },
{ label : 'SPG' },
{ label : 'AMZN' },
{ label : 'LR' },
{ label : 'CBS' },
{ label : 'RIO' },
{ label : 'TLS' },
{ label : 'LTR' },
{ label : 'GENZ' },
{ label : 'RTN' },
{ label : 'TELN' },
{ label : 'LVS' },
{ label : 'FD' },
{ label : 'AL' },
{ label : 'STJ' },
{ label : 'CHT' },
{ label : 'BSX' },
{ label : 'FUJIY' },
{ label : 'XTO' },
{ label : 'K' },
{ label : 'ACE' },
{ label : 'WMI' },
{ label : 'SPLS' },
{ label : 'GIS' },
{ label : 'DHR' },
{ label : 'SKM' },
{ label : 'CD' },
{ label : 'ZMH' },
{ label : 'NWS' },
{ label : 'CRHCY' },
{ label : 'PX' },
{ label : 'WY' },
{ label : 'KYO' },
{ label : 'DE' },
{ label : 'NVO' },
{ label : 'STM' },
{ label : 'IRE' },
{ label : 'PEG' },
{ label : 'MHS' },
{ label : 'MMC' },
{ label : 'TMX' },
{ label : 'FE' },
{ label : 'FPL' },
{ label : 'ERTS' },
{ label : 'LPL' },
{ label : 'PEG' },
{ label : 'MCK' },
{ label : 'PD' },
{ label : 'AU' },
{ label : 'BDX' },
{ label : 'ITU' },
{ label : 'IP' },
{ label : 'BSY' },
{ label : 'WF' },
{ label : 'CA' },
{ label : 'CCU' },
{ label : 'GPS' },
{ label : 'NKE' },
{ label : 'FRX' },
{ label : 'AGN' },
{ label : 'WFT' },
{ label : 'NBG' },
{ label : 'SUNW' },
{ label : 'F' },
{ label : 'KSS' },
{ label : 'SHG' },
{ label : 'CI' },
{ label : 'TRP' },
{ label : 'BIIB' },
{ label : 'RF' },
{ label : 'TP' },
{ label : 'NXY' },
{ label : 'RAI' },
{ label : 'GCI' },
{ label : 'LM' },
{ label : 'KFT' },
{ label : 'OMC' },
{ label : 'MEL' },
{ label : 'HDI' },
{ label : 'AEP' },
{ label : 'CME' },
{ label : 'ADI' },
{ label : 'A' },
{ label : 'ETR' },
{ label : 'AHC' },
{ label : 'KEY' },
{ label : 'WOS' },
{ label : 'BSC' },
{ label : 'GSF' },
{ label : 'TI/A' },
{ label : 'EIX' },
{ label : 'WMB' },
{ label : 'VOLVY' },
{ label : 'YUM' },
{ label : 'PCG' },
{ label : 'IBN' },
{ label : 'TLK' },
{ label : 'MAR' },
{ label : 'SLE' },
{ label : 'AKZOY' },
{ label : 'CCJ' },
{ label : 'PAYX' },
{ label : 'APD' },
{ label : 'COH' },
{ label : 'GM' },
{ label : 'SYT' },
{ label : 'HET' },
{ label : 'EMQ' },
{ label : 'IVV' },
{ label : 'MXIM' },
{ label : 'JCI' },
{ label : 'BOX' },
{ label : 'KR' },
{ label : 'HOT' },
{ label : 'XRX' },
{ label : 'TKG' },
{ label : 'ESRX' },
{ label : 'SHR' },
{ label : 'NOV' },
{ label : 'LUV' },
{ label : 'PFG' },
{ label : 'WPPGY' },
{ label : 'N' },
].map(suggestion => ({
  value: suggestion.label,
  label: suggestion.label,
}));

const useStyles = makeStyles(theme => ({
  root: {
    flexGrow: 1,
    height: 250,
    minWidth: 290,
  },
  input: {
    display: 'flex',
    padding: 0,
    height: 'auto',
  },
  valueContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    flex: 1,
    alignItems: 'center',
    overflow: 'hidden',
  },
  chip: {
    margin: theme.spacing(0.5, 0.25),
  },
  chipFocused: {
    backgroundColor: emphasize(
      theme.palette.type === 'light' ? theme.palette.grey[300] : theme.palette.grey[700],
      0.08,
    ),
  },
  noOptionsMessage: {
    padding: theme.spacing(1, 2),
  },
  singleValue: {
    fontSize: 16,
  },
  placeholder: {
    position: 'absolute',
    left: 2,
    bottom: 6,
    fontSize: 16,
  },
  paper: {
    position: 'absolute',
    zIndex: 1,
    marginTop: theme.spacing(1),
    left: 0,
    right: 0,
  },
  divider: {
    height: theme.spacing(2),
  },
}));

function NoOptionsMessage(props) {
  return (
    <Typography
      color="textSecondary"
      className={props.selectProps.classes.noOptionsMessage}
      {...props.innerProps}
    >
      {props.children}
    </Typography>
  );
}

NoOptionsMessage.propTypes = {
  /**
   * The children to be rendered.
   */
  children: PropTypes.node,
  /**
   * Props to be passed on to the wrapper.
   */
  innerProps: PropTypes.object.isRequired,
  selectProps: PropTypes.object.isRequired,
};

function inputComponent({ inputRef, ...props }) {
  return <div ref={inputRef} {...props} />;
}

inputComponent.propTypes = {
  inputRef: PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.shape({
      current: PropTypes.any.isRequired,
    }),
  ]),
};

function Control(props) {
  const {
    children,
    innerProps,
    innerRef,
    selectProps: { classes, TextFieldProps },
  } = props;

  return (
    <TextField
      fullWidth
      InputProps={{
        inputComponent,
        inputProps: {
          className: classes.input,
          ref: innerRef,
          children,
          ...innerProps,
        },
      }}
      {...TextFieldProps}
    />
  );
}

Control.propTypes = {
  /**
   * Children to render.
   */
  children: PropTypes.node,
  /**
   * The mouse down event and the innerRef to pass down to the controller element.
   */
  innerProps: PropTypes.shape({
    onMouseDown: PropTypes.func.isRequired,
  }).isRequired,
  innerRef: PropTypes.oneOfType([
    PropTypes.oneOf([null]),
    PropTypes.func,
    PropTypes.shape({
      current: PropTypes.any.isRequired,
    }),
  ]).isRequired,
  selectProps: PropTypes.object.isRequired,
};

function Option(props) {
  return (
    <MenuItem
      ref={props.innerRef}
      selected={props.isFocused}
      component="div"
      style={{
        fontWeight: props.isSelected ? 500 : 400,
      }}
      {...props.innerProps}
    >
      {props.children}
    </MenuItem>
  );
}

Option.propTypes = {
  /**
   * The children to be rendered.
   */
  children: PropTypes.node,
  /**
   * props passed to the wrapping element for the group.
   */
  innerProps: PropTypes.shape({
    id: PropTypes.string.isRequired,
    key: PropTypes.string.isRequired,
    onClick: PropTypes.func.isRequired,
    onMouseMove: PropTypes.func.isRequired,
    onMouseOver: PropTypes.func.isRequired,
    tabIndex: PropTypes.number.isRequired,
  }).isRequired,
  /**
   * Inner ref to DOM Node
   */
  innerRef: PropTypes.oneOfType([
    PropTypes.oneOf([null]),
    PropTypes.func,
    PropTypes.shape({
      current: PropTypes.any.isRequired,
    }),
  ]).isRequired,
  /**
   * Whether the option is focused.
   */
  isFocused: PropTypes.bool.isRequired,
  /**
   * Whether the option is selected.
   */
  isSelected: PropTypes.bool.isRequired,
};

function Placeholder(props) {
  const { selectProps, innerProps = {}, children } = props;
  return (
    <Typography color="textSecondary" className={selectProps.classes.placeholder} {...innerProps}>
      {children}
    </Typography>
  );
}

Placeholder.propTypes = {
  /**
   * The children to be rendered.
   */
  children: PropTypes.node,
  /**
   * props passed to the wrapping element for the group.
   */
  innerProps: PropTypes.object,
  selectProps: PropTypes.object.isRequired,
};

function SingleValue(props) {
  return (
    <Typography className={props.selectProps.classes.singleValue} {...props.innerProps}>
      {props.children}
    </Typography>
  );
}

SingleValue.propTypes = {
  /**
   * The children to be rendered.
   */
  children: PropTypes.node,
  /**
   * Props passed to the wrapping element for the group.
   */
  innerProps: PropTypes.any.isRequired,
  selectProps: PropTypes.object.isRequired,
};

function ValueContainer(props) {
  return <div className={props.selectProps.classes.valueContainer}>{props.children}</div>;
}

ValueContainer.propTypes = {
  /**
   * The children to be rendered.
   */
  children: PropTypes.node,
  selectProps: PropTypes.object.isRequired,
};

function MultiValue(props) {
  return (
    <Chip
      tabIndex={-1}
      label={props.children}
      className={clsx(props.selectProps.classes.chip, {
        [props.selectProps.classes.chipFocused]: props.isFocused,
      })}
      onDelete={props.removeProps.onClick}
      deleteIcon={<CancelIcon {...props.removeProps} />}
    />
  );
}

MultiValue.propTypes = {
  children: PropTypes.node,
  isFocused: PropTypes.bool.isRequired,
  removeProps: PropTypes.shape({
    onClick: PropTypes.func.isRequired,
    onMouseDown: PropTypes.func.isRequired,
    onTouchEnd: PropTypes.func.isRequired,
  }).isRequired,
  selectProps: PropTypes.object.isRequired,
};

function Menu(props) {
  return (
    <Paper square className={props.selectProps.classes.paper} {...props.innerProps}>
      {props.children}
    </Paper>
  );
}

Menu.propTypes = {
  /**
   * The children to be rendered.
   */
  children: PropTypes.element.isRequired,
  /**
   * Props to be passed to the menu wrapper.
   */
  innerProps: PropTypes.object.isRequired,
  selectProps: PropTypes.object.isRequired,
};

const components = {
  Control,
  Menu,
  MultiValue,
  NoOptionsMessage,
  Option,
  Placeholder,
  SingleValue,
  ValueContainer,
};

export default function IntegrationReactSelect(props) {
  const classes = useStyles();
  const theme = useTheme();

  const selectStyles = {
    input: base => ({
      ...base,
      color: theme.palette.text.primary,
      '& input': {
        font: 'inherit',
      },
    }),
  };

  return (
    <div className={classes.root}>
      <NoSsr>
        <Select
          classes={classes}
          styles={selectStyles}
          inputId="react-select-multiple"
          TextFieldProps={{
            label: 'Stock Tickers',
            InputLabelProps: {
              htmlFor: 'react-select-multiple',
              shrink: true,
            },
          }}
          placeholder="Select multiple tickers"
          options={suggestions}
          components={components}
          value={props.multi}
          onChange={props.handleChangeMulti}
          isMulti
        />
      </NoSsr>
    </div>
  );
}